/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Controller.Ui;
import com.model.Customer;
import java.sql.Date;
import javax.swing.ButtonGroup;
import com.DataAccessObject.CustomerDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author W10
 */
public class CustomerUi extends javax.swing.JInternalFrame {
    /**
     * Creates new form CustomerUi
     */
    Customer customer=new Customer();
    CustomerDAO custdao=new CustomerDAO();
    public CustomerUi() {
       
        initComponents();
        Cr_btn.setSelected(true);
        groupButoon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void groupButoon(){
        ButtonGroup bg= new ButtonGroup();
        bg.add(Cr_btn);
        bg.add(Dr_btn);
    }
     
      public boolean validateCustomer(){
       if(custname_txt.getText()==null||custname_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter Customer Nane");
           return false;
       } 
       if(address_txt.getText()==null||address_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter Address");
           
           return false;
       }
        if(cityname_txt.getText()==null||cityname_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter City Name");
           
           return false;
       }
        
         if(areacode_txt.getText()==null||areacode_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter Area Code");
           return false;
       }
          if(state_combobox.getSelectedItem()==null||state_combobox.getSelectedItem().equals("")){
           JOptionPane.showMessageDialog(this,"Please Select State");
           
           return false;
       }
           if(contactno1_txt.getText()==null||contactno1_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter Contact Number");
           
           return false;
       }
            if(gstno_txt.getText()==null||gstno_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter GST NO");
           
           return false;
       }
             if(maildid_txt.getText()==null||maildid_txt.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter Email Address");
           
           return false;
       }
          
       
        return true;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Custname_lbl = new javax.swing.JLabel();
        address_lbl = new javax.swing.JLabel();
        cityname_lbl = new javax.swing.JLabel();
        areacode_lbl = new javax.swing.JLabel();
        state_lbl = new javax.swing.JLabel();
        statecode_lbl = new javax.swing.JLabel();
        contactno1_lbl = new javax.swing.JLabel();
        contactno2_lbl = new javax.swing.JLabel();
        contactno3_lbl = new javax.swing.JLabel();
        bankname_lbl = new javax.swing.JLabel();
        IFSCcode_lbl = new javax.swing.JLabel();
        acno_lbl = new javax.swing.JLabel();
        branch_lbl = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        custname_txt = new javax.swing.JTextField();
        cityname_txt = new javax.swing.JTextField();
        areacode_txt = new javax.swing.JTextField();
        statecode_txt = new javax.swing.JTextField();
        contactno1_txt = new javax.swing.JTextField();
        contactno2_txt = new javax.swing.JTextField();
        contactno3_txt = new javax.swing.JTextField();
        Ifsccode_txt = new javax.swing.JTextField();
        bankname_txt = new javax.swing.JTextField();
        acno_txt = new javax.swing.JTextField();
        Submit_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        state_combobox = new javax.swing.JComboBox<>();
        gstno_lbl = new javax.swing.JLabel();
        gstno_txt = new javax.swing.JTextField();
        mailid_lbl = new javax.swing.JLabel();
        maildid_txt = new javax.swing.JTextField();
        DOB_lbl = new javax.swing.JLabel();
        proffesion_txt = new javax.swing.JTextField();
        proffesion_lbl = new javax.swing.JLabel();
        pincode_txt = new javax.swing.JTextField();
        pincode_lbl = new javax.swing.JLabel();
        Dob_DatePicker = new org.jdesktop.swingx.JXDatePicker();
        AnniversaryDob_DatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        openBal_Txt = new javax.swing.JTextField();
        Cr_btn = new javax.swing.JRadioButton();
        Dr_btn = new javax.swing.JRadioButton();
        branch_txt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Creation"));
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Creation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        Custname_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Custname_lbl.setText("Customer Name");

        address_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        address_lbl.setText("Address");

        cityname_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cityname_lbl.setText("City Name");

        areacode_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        areacode_lbl.setText("Area Code");

        state_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        state_lbl.setText("State");

        statecode_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        statecode_lbl.setText("State Code");

        contactno1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        contactno1_lbl.setText("Contact No 1");

        contactno2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        contactno2_lbl.setText("Contact No 2");

        contactno3_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        contactno3_lbl.setText("Contact No 3");

        bankname_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bankname_lbl.setText("Bank Name");

        IFSCcode_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        IFSCcode_lbl.setText("IFSC Code");

        acno_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        acno_lbl.setText("A/C No");

        branch_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        branch_lbl.setText("Branch");

        custname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custname_txtActionPerformed(evt);
            }
        });

        contactno2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactno2_txtActionPerformed(evt);
            }
        });

        contactno3_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactno3_txtActionPerformed(evt);
            }
        });

        Submit_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Submit_btn.setText("Submit");
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        state_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        gstno_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gstno_lbl.setText("Gst No");

        mailid_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mailid_lbl.setText("Mail Id");

        maildid_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maildid_txtActionPerformed(evt);
            }
        });

        DOB_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        DOB_lbl.setText("DOB");

        proffesion_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        proffesion_lbl.setText("Proffesion ");

        pincode_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pincode_lbl.setText("Pin Code");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Anniversary DOB");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("OpenningBalance");

        openBal_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBal_TxtActionPerformed(evt);
            }
        });

        Cr_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Cr_btn.setText("Cr.");
        Cr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cr_btnActionPerformed(evt);
            }
        });

        Dr_btn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Dr_btn.setText("Dr.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(state_lbl)
                    .addComponent(IFSCcode_lbl)
                    .addComponent(branch_lbl)
                    .addComponent(jLabel2)
                    .addComponent(acno_lbl)
                    .addComponent(bankname_lbl)
                    .addComponent(pincode_lbl)
                    .addComponent(proffesion_lbl)
                    .addComponent(gstno_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactno3_lbl)
                    .addComponent(contactno1_lbl)
                    .addComponent(statecode_lbl)
                    .addComponent(DOB_lbl)
                    .addComponent(areacode_lbl)
                    .addComponent(cityname_lbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Custname_lbl)
                            .addComponent(address_lbl)
                            .addComponent(contactno2_lbl)
                            .addComponent(mailid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areacode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statecode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactno1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactno2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactno3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maildid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dob_DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AnniversaryDob_DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(proffesion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pincode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Submit_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear_btn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Cr_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Dr_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(openBal_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addComponent(branch_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(acno_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Ifsccode_txt, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Custname_lbl)
                    .addComponent(custname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityname_lbl)
                    .addComponent(cityname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areacode_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areacode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state_lbl)
                    .addComponent(state_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statecode_lbl)
                    .addComponent(statecode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactno1_lbl)
                    .addComponent(contactno1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactno2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactno2_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactno3_lbl)
                    .addComponent(contactno3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gstno_lbl)
                    .addComponent(gstno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maildid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailid_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB_lbl)
                    .addComponent(Dob_DatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(AnniversaryDob_DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proffesion_lbl)
                    .addComponent(proffesion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pincode_lbl)
                    .addComponent(pincode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankname_lbl)
                    .addComponent(bankname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IFSCcode_lbl)
                    .addComponent(Ifsccode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acno_lbl)
                    .addComponent(acno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branch_lbl)
                    .addComponent(branch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cr_btn)
                    .addComponent(Dr_btn)
                    .addComponent(openBal_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_btn)
                    .addComponent(clear_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 883, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void contactno2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactno2_txtActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_contactno2_txtActionPerformed

    private void contactno3_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactno3_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactno3_txtActionPerformed

    private void maildid_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maildid_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maildid_txtActionPerformed

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
          if(!validateCustomer()){
              return;
          }
         
        
          customer.setCustName(custname_txt.getText());
          customer.setAdress(address_txt.getText());
          customer.setCityName(cityname_txt.getText());
          customer.setAreaCode(areacode_txt.getText());
          customer.setState((String)state_combobox.getSelectedItem());
          customer.setStateCode(statecode_txt.getText());
          customer.setContactNo1(contactno1_txt.getText());
          customer.setContactNo2(contactno2_txt.getText());
          customer.setContactNo3(contactno3_txt.getText());
          customer.setGstin(gstno_txt.getText());
          customer.setEmail(maildid_txt.getText());
          customer.setDob(new java.sql.Date(Dob_DatePicker.getDate().getTime()));
          customer.setAnnivarsaryDate(new java.sql.Date(AnniversaryDob_DatePicker.getDate().getTime()));
          customer.setProfession(proffesion_txt.getText());
          customer.setPincode(Integer.valueOf((String)(pincode_txt.getText())));
          customer.setBankName(bankname_txt.getText());
          customer.setAccNo(acno_txt.getText());
          customer.setIfsc(Ifsccode_txt.getText());
          customer.setBankBranch(branch_txt.getText());
          if(Cr_btn.isSelected()){
            customer.setOpeningBalance(Double.parseDouble(openBal_Txt.getText()));
        }else{
            customer.setOpeningBalance(Double.parseDouble(openBal_Txt.getText()));
        }
          custdao.createCustomer(customer);
          
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void openBal_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBal_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBal_TxtActionPerformed

    private void Cr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cr_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cr_btnActionPerformed

    private void custname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custname_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker AnniversaryDob_DatePicker;
    private javax.swing.JRadioButton Cr_btn;
    private javax.swing.JLabel Custname_lbl;
    private javax.swing.JLabel DOB_lbl;
    private org.jdesktop.swingx.JXDatePicker Dob_DatePicker;
    private javax.swing.JRadioButton Dr_btn;
    private javax.swing.JLabel IFSCcode_lbl;
    private javax.swing.JTextField Ifsccode_txt;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JLabel acno_lbl;
    private javax.swing.JTextField acno_txt;
    private javax.swing.JLabel address_lbl;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel areacode_lbl;
    private javax.swing.JTextField areacode_txt;
    private javax.swing.JLabel bankname_lbl;
    private javax.swing.JTextField bankname_txt;
    private javax.swing.JLabel branch_lbl;
    private javax.swing.JTextField branch_txt;
    private javax.swing.JLabel cityname_lbl;
    private javax.swing.JTextField cityname_txt;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel contactno1_lbl;
    private javax.swing.JTextField contactno1_txt;
    private javax.swing.JLabel contactno2_lbl;
    private javax.swing.JTextField contactno2_txt;
    private javax.swing.JLabel contactno3_lbl;
    private javax.swing.JTextField contactno3_txt;
    private javax.swing.JTextField custname_txt;
    private javax.swing.JLabel gstno_lbl;
    private javax.swing.JTextField gstno_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maildid_txt;
    private javax.swing.JLabel mailid_lbl;
    private javax.swing.JTextField openBal_Txt;
    private javax.swing.JLabel pincode_lbl;
    private javax.swing.JTextField pincode_txt;
    private javax.swing.JLabel proffesion_lbl;
    private javax.swing.JTextField proffesion_txt;
    private javax.swing.JComboBox<String> state_combobox;
    private javax.swing.JLabel state_lbl;
    private javax.swing.JLabel statecode_lbl;
    private javax.swing.JTextField statecode_txt;
    // End of variables declaration//GEN-END:variables
}
