/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Controller.Ui;
import com.model.Item;
import com.DataAccessObject.ItemDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author W10
 */
public class ItemsUi extends javax.swing.JInternalFrame {

    /**
     * Creates new form ItemsUi
     */
    
    Item item=new Item();
    ItemDAO itemdao=new ItemDAO();
//        String Itemname;
//        String hsn;
//        String unit;
//        String style;
//        String color;
//        String size;
//        String group;
//        String subgroup;
//        String gstPer;
//        String gstgroup;
//        int sellingprice;
//        String barcode;
//        int purchaseprice;
//        int openingstock;
        boolean VFalg=false;
    public ItemsUi() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ItemName_LBL = new javax.swing.JLabel();
        hsnCode_LBL = new javax.swing.JLabel();
        unit_LBL = new javax.swing.JLabel();
        style_LBL = new javax.swing.JLabel();
        color_LBL = new javax.swing.JLabel();
        size_LBL = new javax.swing.JLabel();
        group_LBL = new javax.swing.JLabel();
        subgroup_LBL = new javax.swing.JLabel();
        gst_LBL = new javax.swing.JLabel();
        gstgroup_LBL = new javax.swing.JLabel();
        salingprice_LBL = new javax.swing.JLabel();
        barcode_LBL = new javax.swing.JLabel();
        purchaseprise_LBL = new javax.swing.JLabel();
        openningstock_LBL = new javax.swing.JLabel();
        gstGroup_combobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        itemname_txt = new javax.swing.JTextField();
        hsnCode_txt = new javax.swing.JTextField();
        unit_txt = new javax.swing.JTextField();
        style_txt = new javax.swing.JTextField();
        size_txt = new javax.swing.JTextField();
        group_txt = new javax.swing.JTextField();
        color_txt = new javax.swing.JTextField();
        sellingPrice_txt = new javax.swing.JTextField();
        gst_ComboBox = new javax.swing.JComboBox<>();
        subgroup_txt = new javax.swing.JTextField();
        barcode_txt = new javax.swing.JTextField();
        purchaseprice_txt = new javax.swing.JTextField();
        openningStock_txt = new javax.swing.JTextField();

        ItemName_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ItemName_LBL.setText("Item Name");

        hsnCode_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        hsnCode_LBL.setText("HSN Code");

        unit_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        unit_LBL.setText("Unit");

        style_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        style_LBL.setText("Style");

        color_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        color_LBL.setText("Color");

        size_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        size_LBL.setText("Size");

        group_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        group_LBL.setText("Group");

        subgroup_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        subgroup_LBL.setText("Sub Group");

        gst_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gst_LBL.setText("Gst %");

        gstgroup_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gstgroup_LBL.setText("Gst Group");

        salingprice_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        salingprice_LBL.setText("Salling Price ");

        barcode_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        barcode_LBL.setText("Barcode ");

        purchaseprise_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        purchaseprise_LBL.setText("Purchase Price");

        openningstock_LBL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        openningstock_LBL.setText("Openning Stock");

        gstGroup_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Clear");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hsnCode_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsnCode_txtActionPerformed(evt);
            }
        });

        gst_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        purchaseprice_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseprice_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemName_LBL)
                            .addComponent(hsnCode_LBL)
                            .addComponent(unit_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(style_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(group_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subgroup_LBL)
                            .addComponent(gst_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstgroup_LBL)
                            .addComponent(barcode_LBL))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcode_txt)
                            .addComponent(hsnCode_txt)
                            .addComponent(itemname_txt)
                            .addComponent(unit_txt)
                            .addComponent(style_txt)
                            .addComponent(color_txt)
                            .addComponent(size_txt)
                            .addComponent(group_txt)
                            .addComponent(subgroup_txt)
                            .addComponent(sellingPrice_txt)
                            .addComponent(gst_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gstGroup_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(openningstock_LBL)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(openningStock_txt))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salingprice_LBL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(purchaseprise_LBL)
                        .addGap(18, 18, 18)
                        .addComponent(purchaseprice_txt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemName_LBL)
                    .addComponent(itemname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hsnCode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsnCode_LBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit_LBL)
                    .addComponent(unit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(style_LBL)
                    .addComponent(style_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color_LBL)
                    .addComponent(color_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size_LBL)
                    .addComponent(size_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(group_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(group_LBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subgroup_LBL)
                    .addComponent(subgroup_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gst_LBL)
                    .addComponent(gst_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gstGroup_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstgroup_LBL))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salingprice_LBL)
                    .addComponent(sellingPrice_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcode_LBL)
                    .addComponent(barcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseprise_LBL)
                    .addComponent(purchaseprice_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openningstock_LBL)
                    .addComponent(openningStock_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(811, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hsnCode_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsnCode_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsnCode_txtActionPerformed

    private void purchaseprice_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseprice_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseprice_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SubmitItemEntry();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemName_LBL;
    private javax.swing.JLabel barcode_LBL;
    private javax.swing.JTextField barcode_txt;
    private javax.swing.JLabel color_LBL;
    private javax.swing.JTextField color_txt;
    private javax.swing.JLabel group_LBL;
    private javax.swing.JTextField group_txt;
    private javax.swing.JComboBox<String> gstGroup_combobox;
    private javax.swing.JComboBox<String> gst_ComboBox;
    private javax.swing.JLabel gst_LBL;
    private javax.swing.JLabel gstgroup_LBL;
    private javax.swing.JLabel hsnCode_LBL;
    private javax.swing.JTextField hsnCode_txt;
    private javax.swing.JTextField itemname_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField openningStock_txt;
    private javax.swing.JLabel openningstock_LBL;
    private javax.swing.JTextField purchaseprice_txt;
    private javax.swing.JLabel purchaseprise_LBL;
    private javax.swing.JLabel salingprice_LBL;
    private javax.swing.JTextField sellingPrice_txt;
    private javax.swing.JLabel size_LBL;
    private javax.swing.JTextField size_txt;
    private javax.swing.JLabel style_LBL;
    private javax.swing.JTextField style_txt;
    private javax.swing.JLabel subgroup_LBL;
    private javax.swing.JTextField subgroup_txt;
    private javax.swing.JLabel unit_LBL;
    private javax.swing.JTextField unit_txt;
    // End of variables declaration//GEN-END:variables

    
    private boolean validatItemForm() {

        return VFalg;
    }
    private void SubmitItemEntry() {
        try {
            if(!validatItemForm()){
                
            }
            item.setItemname(itemname_txt.getText());
            item.setHsn(hsnCode_txt.getText());
            item.setUnit(unit_txt.getText());
            item.setStyle(style_txt.getText());
            item.setColor(color_txt.getText());
            item.setSize(size_txt.getText());
            item.setGroup(group_txt.getText());
            item.setSubgroup(subgroup_txt.getText());
            item.setGstPer(gst_ComboBox.getSelectedItem().toString());
            item.setGstgroup(gstGroup_combobox.getSelectedItem().toString());
            item.setSellingprice(Integer.parseInt(sellingPrice_txt.getText()));
            item.setBarcode(barcode_txt.getText());
            item.setPurchaseprice(Integer.parseInt(purchaseprice_txt.getText()));
            item.setOpeningstock(Integer.parseInt(openningStock_txt.getText()));
            
         boolean addProduct = itemdao.addProduct(item);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemsUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    } 
}
